Task three
barty008/backend-project pull request #4
Opened 2023-11-21 14:59 UTC by barty008

2023-11-21 15:48 UTC, 2202Hannah requested changes
Hi James, really nice work on task 3 and task 4 :) There are some changes to be made/ things to add. Please see my in-line comments and a summary for each below. 

**Task 3** 
- Really interesting and creative use of beforeAll() to store the endpoints data in scope!

**Task 4**
- Please update your test to include the exact values for article 10. 
- You will also need to include your tests for error handling as mentioned in my in-line comments.

2023-11-21 15:48 UTC, 2202Hannah commented on __tests__/app.test.js
> +        })
Great use of toMatchObject here!

As we know the exact article we are expecting we should use the exact values here rather than the data types.

2023-11-21 15:48 UTC, 2202Hannah commented on __tests__/app.test.js
> +  })
We should also have tests for error handling for this endpoint. You should consider the following:

- 400 an invalid id e.g. `GET /api/articles/notanumber`
- 404 an article id that doesn't exist in the database `GET /api/articles/9999`

2023-11-21 15:48 UTC, 2202Hannah commented on controller/controller.js
> +      // console.log(endpoints, " end points")
Please remove this console.log

2023-11-22 09:32 UTC, Hard-Luck requested changes
Really close you just need to add messages to the response body

2023-11-22 09:32 UTC, Hard-Luck commented on __tests__/app.test.js
> +    return request(app).get("/api/articles/notanumber").expect(400)
these should both have a msg on the body of the response, "not found" and "bad request" or something similar

2023-11-22 16:26 UTC, merged